"use client";

import { AppShell } from "@/components/layout/AppShell";
import { DetectorPanel } from "@/components/features/DetectorPanel";

export default function DetectorPage() {
  return (
    <AppShell>
      <div className="mb-6">
        <h1 className="text-3xl font-bold mb-2">AI Detector</h1>
        <p className="text-muted-foreground">
          Detect probability that content was generated by AI with span-level analysis
        </p>
      </div>
      <DetectorPanel />
    </AppShell>
  );
}